//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebScraping
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public int codigo { get; set; }
        public string urlFoto { get; set; }
        public string descricao { get; set; }
        public string lanceInicial { get; set; }
        public string maiorLance { get; set; }
        public Nullable<int> quantidadeLances { get; set; }
    }
}
